version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nexus-nginx
    ports:
      - "443:443"  # Porta HTTPS para o acesso ao front-end do Nexus e Docker Registry
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro  # Certificados autoassinados
    depends_on:
      - nexus
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"  # Porta interna para o front-end do Nexus
      - "5000:5000"  # Porta para o repositório Docker Hosted
      - "5001:5001"  # Porta para o repositório Docker Proxy
    volumes:
      - nexus-data:/nexus-data
      - nexus-logs:/nexus-logs

volumes:
  nexus-data:
  nexus-logs:
